Repository italiangrid/storm-webdav, pull requests merged in 2024-12, with the labels that each got.

#74 Skip invalid DN into the VO map file
  src/main/java/org/italiangrid/storm/webdav/authz/vomap/MapfileVOMembershipSource.java
  src/test/java/org/italiangrid/storm/webdav/test/authz/vomap/VOMSMapTests.java
  src/test/resources/vomsmap/testers.map
Labels: bug

#59 Support for the 'entitlements' JWT claim
  src/main/java/org/italiangrid/storm/webdav/oauth/GrantedAuthoritiesMapperSupport.java
  src/test/java/org/italiangrid/storm/webdav/test/authz/integration/AuthorizationIntegrationTests.java
Labels: enhancement, priority/high

#67 update milton version from v2.7.1.7 to v2.8.0.3
  pom.xml
Labels: dependencies
