Repository italiangrid/storm-webdav, pull requests merged in 2025-02, with the labels that each got.

#80 Add robots.txt to disallow all web crawlers
  src/main/java/org/italiangrid/storm/webdav/spring/web/SecurityConfig.java
  src/main/java/org/italiangrid/storm/webdav/web/RobotsTxtController.java
Labels: enhancement, priority/low, task

#82 Add v1.5.0 release to CHANGELOG.md
  CHANGELOG.md
Labels: priority/low, task

#81 Improve systemd service unit
  etc/systemd/system/storm-webdav.service
Labels: enhancement, priority/normal, task
